version: '3.7'
services:
  ec_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=emptycabinet
    ports:
      - '5438:5432'
